[Fix] OnBoarding
Black-Bank/Black-Wallet pull request #51
Opened 2023-06-28 20:14 UTC by eduardohenri22

2023-06-28 20:15 UTC, eduardohenri22 reviewed
Corrigindo tamanhos de textos na onboarding.

2023-06-28 20:17 UTC, maksonss4 approved these changes

2023-06-28 20:25 UTC, Cyro56 requested changes
Vamos posicionar os elementos na tela com flex-box para melhor responsividade. Ao posicionar com margin-bottom nessa situação teremos problemas de responsividade nos diferentes dispositivos.

2023-06-30 20:10 UTC, Cyro56 approved these changes

2023-06-30 20:11 UTC, merged